name: ✨ Feature Request
description: Suggest a new feature or enhancement for JARVIS
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting improvements to JARVIS! Your ideas help shape the future of conversational computing.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature you'd like to see
      placeholder: "I would like JARVIS to..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        Currently, when I try to..., I have to...
        This is frustrating because...
        A better solution would be...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        I imagine saying "JARVIS, ..." and having it:
        1. Do this...
        2. Then this...
        3. Finally this...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - New Skill
        - Skill Enhancement
        - Workflow Automation
        - AI Intelligence
        - User Interface
        - Performance
        - Integration
        - Security/Privacy
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to your productivity?
      options:
        - Critical - I can't use JARVIS effectively without this
        - High - This would significantly improve my workflow
        - Medium - This would be a nice quality of life improvement
        - Low - This is just a cool idea
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any workarounds or alternative approaches?
      placeholder: "I currently work around this by..."

  - type: textarea
    id: examples
    attributes:
      label: Example Commands
      description: What specific commands would you use with this feature?
      placeholder: |
        "JARVIS, ..."
        "JARVIS, ..."
        "JARVIS, ..."

  - type: input
    id: references
    attributes:
      label: References
      description: Any relevant links, apps, or examples that inspired this feature?
      placeholder: "Similar to [app/feature], or see [link]"

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      options:
        - label: I'd be willing to help implement this feature
        - label: I could provide testing and feedback
        - label: I could help with documentation
        - label: I'm just suggesting the idea

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I've searched existing issues and feature requests
          required: true
        - label: I've considered how this fits with JARVIS's conversational philosophy
          required: true
        - label: I've provided clear examples and use cases
          required: true